project:
  type: website
  output-dir: docs

website:
  title: "Isabell Victoria Strandby Ernst"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: My Art
        href: myart.qmd

format:
  html:
    theme: none
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500&family=Inter:wght@300;400&display=swap" rel="stylesheet">




